exclude: '^$'
default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
    - id: flake8

# -   repo: https://github.com/PyCQA/bandit
#     rev: 'master'
#     hooks:
#     - id: bandit
#       exclude: venv|tests